### ISSUE TITLE
Settings awry on install?

### ISSUE THREAD

**Issue by nikdavis** [bradleyboy/TidyTabs-Sublime#10]
I'm installing through https://packagecontrol.io/. Through the menu, package settings are blank by default and there are no user settings files available 

All through Preferences -> Package Settings -> Tidy Tabs

![screen shot 2015-01-25 at 6 41 59 pm](https://cloud.githubusercontent.com/assets/3935178/5894755/e1fb4a9a-a4c1-11e4-94e1-6b1e33b81139.png)

**Comment by dsnipe** [comment]
@nikdavis fixes in PR #9 
It solve the problem, so you can using my fork, or make same fixes by yourself. 
Or maybe @bradleyboy can merge it?

**Comment by bradleyboy** [comment]
Sorry I missed this everyone, I'm not using Sublime much these days. I'll merge that PR now.
